version: '3'
services:
  seakngim:
    #image: it for name your image after docker build -t nameyourimages .
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 50002:3000